"
The MiscPharoScripts Project is my various extensions, applications, and throw away ideas in Pharo. Some ideas may be intersting, while other functions are utterly mundane and used to explore Pharo itself.
"
Class {
	#name : #ManifestBaselineOfMiscPharoScripts,
	#superclass : #PackageManifest,
	#category : 'BaselineOfMiscPharoScripts-Manifest'
}

{ #category : #'code-critics' }
ManifestBaselineOfMiscPharoScripts class >> ruleClassNotReferencedRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#BaselineOfMiscPharoScripts)) #'2022-10-20T23:38:15.38804+08:00') )
]
